#include <furi.h>

/* generated by fbt from .png files in images folder */
#include <factory_u2f_crack_icons.h>

int32_t factory_u2f_crack_app(void* p) {
    UNUSED(p);
    FURI_LOG_I("TEST", "Hello world");
    FURI_LOG_I("TEST", "I'm factory_u2f_crack!");

    return 0;
}
