name: "FAP: Build for multiple SDK sources"
# This will build your app for dev and release channels on GitHub. 
# It will also build your app every day to make sure it's up to date with the latest SDK changes.
# See https://github.com/marketplace/actions/build-flipper-application-package-fap for more information

on:
  push:
    tags:
      - "v*.*.*"   # 可根据实际情况指定tag格式，例如: "v1.0.0"

jobs:
  ufbt-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: dev channel
            sdk-channel: dev
          - name: release channel
            sdk-channel: release
          # You can add unofficial channels here. See ufbt action docs for more info.
    name: 'ufbt: Build for ${{ matrix.name }}'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build with ufbt
        uses: flipperdevices/flipperzero-ufbt-action@v0.1.3
        id: build-app
        with:
          sdk-channel: ${{ matrix.sdk-channel }}

      - name: Upload app artifacts
        uses: actions/upload-artifact@v4
        with:
          # See ufbt action docs for other output variables
          name: ${{ github.event.repository.name }}-${{ steps.build-app.outputs.suffix }}
          path: ${{ steps.build-app.outputs.fap-artifacts }}

      - name: Rename
        id: rename
        run: |
          DIRECTORY_PATH="${{ steps.build-app.outputs.fap-artifacts }}"
          SUFFIX="${{ steps.build-app.outputs.suffix }}"

          # 获取文件的目录路径
          DIR_PATH=$(dirname "$DIRECTORY_PATH")
          BASENAME=$(basename "$DIRECTORY_PATH")
          
          # 检查是否是文件
          if [ -f "$DIRECTORY_PATH" ]; then
            # 获取文件名和扩展名
            EXTENSION="${BASENAME##*.}"
            FILENAME="${BASENAME%.*}"

            # 新文件名
            NEW_NAME="${FILENAME}-${SUFFIX}.${EXTENSION}"

            # 重命名文件
            mv "$DIRECTORY_PATH" "$DIR_PATH/$NEW_NAME"

            # 输出重命名后的文件路径
            echo "new_file_path=$DIR_PATH/$NEW_NAME" >> $GITHUB_ENV
          fi

          # 输出重命名后的文件列表
          echo "Renamed file:"
          ls "$DIR_PATH"

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          draft: false
          artifacts: ${{ env.new_file_path }}
          allowUpdates: true
          token: ${{ secrets.TOKEN }}
